In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("inventory.csv")

In [4]:
df.head()

   ProductID ProductName     Category  Stock  Price  Supplier LastUpdated
0        101      Laptop  Electronics     50  60000      Dell  01-04-2026
1        102       Mouse  Electronics    200    500  Logitech  05-04-2026
2        103    Keyboard  Electronics    150   1500        HP  03-04-2026
3        104       Chair    Furniture     80   3000      IKEA  02-04-2026
4        105        Desk    Furniture     40   7000      IKEA  01-04-2026

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ProductID    5 non-null      int64
 1   ProductName  5 non-null      object
 2   Category     5 non-null      object
 3   Stock        5 non-null      int64
 4   Price        5 non-null      int64
 5   Supplier     5 non-null      object
 6   LastUpdated  5 non-null      object
dtypes: int64(3), object(4)
memory usage: 412.0+ bytes

In [7]:
df.describe()

        ProductID       Stock         Price
count    5.000000    5.000000      5.000000
mean   103.000000  104.000000  14400.000000
std      1.581139   68.774995  25611.032779
min    101.000000   40.000000    500.000000
25%    102.000000   50.000000   1500.000000
50%    103.000000   80.000000   3000.000000
75%    104.000000  150.000000   7000.000000
max    105.000000  200.000000  60000.000000

# 🧮 Step 5: Add New Column (Total Value)
## 👉 Total Value = Stock × Price

In [10]:
df["TotalValue"] = df["Stock"] * df["Price"]
df

,ProductID,ProductName,Category,Stock,Price,Supplier,LastUpdated,TotalValue
0,101,Laptop,Electronics,50,60000,Dell,01-04-2026,3000000
1,102,Mouse,Electronics,200,500,Logitech,05-04-2026,100000
2,103,Keyboard,Electronics,150,1500,HP,03-04-2026,225000
3,104,Chair,Furniture,80,3000,IKEA,02-04-2026,240000
4,105,Desk,Furniture,40,7000,IKEA,01-04-2026,280000

# ⚠️ Step 6: Find Low Stock Items

## 👉 Example: Stock < 50

In [14]:
low_stock = df[df["Stock"] < 50]
low_stock

,ProductID,ProductName,Category,Stock,Price,Supplier,LastUpdated,TotalValue
4,105,Desk,Furniture,40,7000,IKEA,01-04-2026,280000

# Step 7: Category-wise Analysis

In [18]:
category_wise = df.groupby("Category")["TotalValue"].sum()
category_wise

Category
Electronics    3325000
Furniture       520000
Name: TotalValue, dtype: int64

# 🏆 Step 8: Top Expensive Products

In [28]:
top_products = df.sort_values(by="Price",ascending = False)
top_products

,ProductID,ProductName,Category,Stock,Price,Supplier,LastUpdated,TotalValue
0,101,Laptop,Electronics,50,60000,Dell,01-04-2026,3000000
4,105,Desk,Furniture,40,7000,IKEA,01-04-2026,280000
3,104,Chair,Furniture,80,3000,IKEA,02-04-2026,240000
2,103,Keyboard,Electronics,150,1500,HP,03-04-2026,225000
1,102,Mouse,Electronics,200,500,Logitech,05-04-2026,100000

In [29]:
df.loc[df["ProductName"] == "Laptop", "Stock"] = 45
df

,ProductID,ProductName,Category,Stock,Price,Supplier,LastUpdated,TotalValue
0,101,Laptop,Electronics,45,60000,Dell,01-04-2026,3000000
1,102,Mouse,Electronics,200,500,Logitech,05-04-2026,100000
2,103,Keyboard,Electronics,150,1500,HP,03-04-2026,225000
3,104,Chair,Furniture,80,3000,IKEA,02-04-2026,240000
4,105,Desk,Furniture,40,7000,IKEA,01-04-2026,280000

In [31]:
df.loc[df["Category"] == "Furniture", "Stock"] = 150
df

,ProductID,ProductName,Category,Stock,Price,Supplier,LastUpdated,TotalValue
0,101,Laptop,Electronics,45,60000,Dell,01-04-2026,3000000
1,102,Mouse,Electronics,200,500,Logitech,05-04-2026,100000
2,103,Keyboard,Electronics,150,1500,HP,03-04-2026,225000
3,104,Chair,Furniture,150,3000,IKEA,02-04-2026,240000
4,105,Desk,Furniture,150,7000,IKEA,01-04-2026,280000

In [32]:
df.loc[df["ProductName"] == "Desk", "Stock"] = 70
df

,ProductID,ProductName,Category,Stock,Price,Supplier,LastUpdated,TotalValue
0,101,Laptop,Electronics,45,60000,Dell,01-04-2026,3000000
1,102,Mouse,Electronics,200,500,Logitech,05-04-2026,100000
2,103,Keyboard,Electronics,150,1500,HP,03-04-2026,225000
3,104,Chair,Furniture,150,3000,IKEA,02-04-2026,240000
4,105,Desk,Furniture,70,7000,IKEA,01-04-2026,280000

# 💾 Step 10: Save Updated Data

In [33]:
df.to_csv("Updated_Inventory.csv", index = False)